language: c
script: make
#addons:
#  apt:
#    packages: 
#    - libsdl1.2-dev 
#    - gcc-mingw-w64
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libsdl1.2-dev binutils-mingw-w64-i686 gcc-wingw-w64-i686
sudo: true
#deploy:
#  provider: releases
#  file: bd_test
#  skip_cleanup: true
